/* AUTO-GENERATED by scripts/generate-portfolio.mjs — do not edit by hand.
 * Run `npm run dev` or `npm run build` to regenerate after adding folders. */

export interface PortfolioImage {
  src: string;
  /** Intrinsic pixel size, read from the file header. */
  width: number | null;
  height: number | null;
}

export interface PortfolioProject {
  slug: string;
  folder: string;
  title: string;
  category: string;
  /** Derived from the source file dates — see yearFor() in the generator. */
  year: string;
  description: string;
  cover: PortfolioImage;
  images: PortfolioImage[];
}

export const portfolioProjects: PortfolioProject[] = [
  {
    "slug": "portfolio-1",
    "folder": "Portfolio-1",
    "title": "Project 01",
    "category": "Branding",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-1/WhatsApp%20Image%202026-07-21%20at%2011.13.21%20AM.jpeg",
      "width": 1185,
      "height": 561
    },
    "images": [
      {
        "src": "/Portfolio-1/WhatsApp%20Image%202026-07-21%20at%2011.13.21%20AM.jpeg",
        "width": 1185,
        "height": 561
      },
      {
        "src": "/Portfolio-1/WhatsApp%20Image%202026-07-21%20at%2011.13.31%20AM%20(1).jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-1/WhatsApp%20Image%202026-07-21%20at%2011.13.31%20AM.jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-1/WhatsApp%20Image%202026-07-21%20at%2011.13.32%20AM%20(1).jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-1/WhatsApp%20Image%202026-07-21%20at%2011.13.32%20AM%20(2).jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-1/WhatsApp%20Image%202026-07-21%20at%2011.13.32%20AM%20(3).jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-1/WhatsApp%20Image%202026-07-21%20at%2011.13.32%20AM.jpeg",
        "width": 960,
        "height": 1280
      }
    ]
  },
  {
    "slug": "portfolio-2",
    "folder": "Portfolio-2",
    "title": "Project 02",
    "category": "Social Media",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-2/WhatsApp%20Image%202026-07-21%20at%2011.15.18%20AM.jpeg",
      "width": 1280,
      "height": 467
    },
    "images": [
      {
        "src": "/Portfolio-2/WhatsApp%20Image%202026-07-21%20at%2011.15.18%20AM.jpeg",
        "width": 1280,
        "height": 467
      },
      {
        "src": "/Portfolio-2/WhatsApp%20Image%202026-07-21%20at%2011.16.13%20AM.jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-2/WhatsApp%20Image%202026-07-21%20at%2011.16.14%20AM%20(1).jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-2/WhatsApp%20Image%202026-07-21%20at%2011.16.14%20AM.jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-2/WhatsApp%20Image%202026-07-21%20at%2011.16.15%20AM%20(1).jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-2/WhatsApp%20Image%202026-07-21%20at%2011.16.15%20AM%20(2).jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-2/WhatsApp%20Image%202026-07-21%20at%2011.16.15%20AM%20(3).jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-2/WhatsApp%20Image%202026-07-21%20at%2011.16.15%20AM.jpeg",
        "width": 960,
        "height": 1280
      }
    ]
  },
  {
    "slug": "portfolio-3",
    "folder": "Portfolio-3",
    "title": "Project 03",
    "category": "Packaging",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-3/WhatsApp%20Image%202026-07-21%20at%2011.17.23%20AM.jpeg",
      "width": 1185,
      "height": 561
    },
    "images": [
      {
        "src": "/Portfolio-3/WhatsApp%20Image%202026-07-21%20at%2011.17.23%20AM.jpeg",
        "width": 1185,
        "height": 561
      },
      {
        "src": "/Portfolio-3/WhatsApp%20Image%202026-07-21%20at%2011.18.09%20AM%20(1).jpeg",
        "width": 960,
        "height": 1280
      },
      {
        "src": "/Portfolio-3/WhatsApp%20Image%202026-07-21%20at%2011.18.09%20AM%20(2).jpeg",
        "width": 1024,
        "height": 1280
      },
      {
        "src": "/Portfolio-3/WhatsApp%20Image%202026-07-21%20at%2011.18.09%20AM%20(3).jpeg",
        "width": 1024,
        "height": 1280
      },
      {
        "src": "/Portfolio-3/WhatsApp%20Image%202026-07-21%20at%2011.18.09%20AM.jpeg",
        "width": 960,
        "height": 1280
      }
    ]
  },
  {
    "slug": "portfolio-4",
    "folder": "Portfolio-4",
    "title": "Project 04",
    "category": "Illustration",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-4/WhatsApp%20Image%202026-07-21%20at%2011.19.21%20AM.jpeg",
      "width": 1600,
      "height": 583
    },
    "images": [
      {
        "src": "/Portfolio-4/WhatsApp%20Image%202026-07-21%20at%2011.19.21%20AM.jpeg",
        "width": 1600,
        "height": 583
      },
      {
        "src": "/Portfolio-4/WhatsApp%20Image%202026-07-21%20at%2011.20.13%20AM.jpeg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/Portfolio-4/WhatsApp%20Image%202026-07-21%20at%2011.20.14%20AM%20(1).jpeg",
        "width": 1080,
        "height": 1080
      },
      {
        "src": "/Portfolio-4/WhatsApp%20Image%202026-07-21%20at%2011.20.14%20AM%20(2).jpeg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/Portfolio-4/WhatsApp%20Image%202026-07-21%20at%2011.20.14%20AM.jpeg",
        "width": 1080,
        "height": 1440
      }
    ]
  },
  {
    "slug": "portfolio-5",
    "folder": "Portfolio-5",
    "title": "Project 05",
    "category": "Branding",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-5/WhatsApp%20Image%202026-07-21%20at%2011.20.30%20AM.jpeg",
      "width": 1600,
      "height": 583
    },
    "images": [
      {
        "src": "/Portfolio-5/WhatsApp%20Image%202026-07-21%20at%2011.20.30%20AM.jpeg",
        "width": 1600,
        "height": 583
      },
      {
        "src": "/Portfolio-5/WhatsApp%20Image%202026-07-21%20at%2011.25.00%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-5/WhatsApp%20Image%202026-07-21%20at%2011.25.00%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-5/WhatsApp%20Image%202026-07-21%20at%2011.25.01%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-5/WhatsApp%20Image%202026-07-21%20at%2011.25.02%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-5/WhatsApp%20Image%202026-07-21%20at%2011.25.02%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-5/WhatsApp%20Image%202026-07-21%20at%2011.25.03%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-5/WhatsApp%20Image%202026-07-21%20at%2011.25.03%20AM.jpeg",
        "width": 1200,
        "height": 1600
      }
    ]
  },
  {
    "slug": "portfolio-6",
    "folder": "Portfolio-6",
    "title": "Project 06",
    "category": "Social Media",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-6/WhatsApp%20Image%202026-07-21%20at%2011.26.19%20AM%20(1).jpeg",
      "width": 1600,
      "height": 1067
    },
    "images": [
      {
        "src": "/Portfolio-6/WhatsApp%20Image%202026-07-21%20at%2011.26.19%20AM%20(1).jpeg",
        "width": 1600,
        "height": 1067
      },
      {
        "src": "/Portfolio-6/WhatsApp%20Image%202026-07-21%20at%2011.26.19%20AM%20(2).jpeg",
        "width": 1600,
        "height": 1067
      },
      {
        "src": "/Portfolio-6/WhatsApp%20Image%202026-07-21%20at%2011.26.19%20AM.jpeg",
        "width": 1600,
        "height": 1067
      }
    ]
  },
  {
    "slug": "portfolio-7",
    "folder": "Portfolio-7",
    "title": "Project 07",
    "category": "Packaging",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-7/WhatsApp%20Image%202026-07-21%20at%2011.32.07%20AM.jpeg",
      "width": 1200,
      "height": 1600
    },
    "images": [
      {
        "src": "/Portfolio-7/WhatsApp%20Image%202026-07-21%20at%2011.32.07%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-7/WhatsApp%20Image%202026-07-21%20at%2011.32.08%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-7/WhatsApp%20Image%202026-07-21%20at%2011.32.08%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-7/WhatsApp%20Image%202026-07-21%20at%2011.32.09%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-7/WhatsApp%20Image%202026-07-21%20at%2011.32.09%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-7/WhatsApp%20Image%202026-07-21%20at%2011.32.10%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-7/WhatsApp%20Image%202026-07-21%20at%2011.32.10%20AM.jpeg",
        "width": 1200,
        "height": 1600
      }
    ]
  },
  {
    "slug": "portfolio-8",
    "folder": "Portfolio-8",
    "title": "Project 08",
    "category": "Illustration",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-8/WhatsApp%20Image%202026-07-21%20at%2011.32.21%20AM.jpeg",
      "width": 1600,
      "height": 667
    },
    "images": [
      {
        "src": "/Portfolio-8/WhatsApp%20Image%202026-07-21%20at%2011.32.21%20AM.jpeg",
        "width": 1600,
        "height": 667
      },
      {
        "src": "/Portfolio-8/WhatsApp%20Image%202026-07-21%20at%2011.32.34%20AM%20(1).jpeg",
        "width": 1080,
        "height": 1448
      },
      {
        "src": "/Portfolio-8/WhatsApp%20Image%202026-07-21%20at%2011.32.34%20AM%20(2).jpeg",
        "width": 1080,
        "height": 1448
      },
      {
        "src": "/Portfolio-8/WhatsApp%20Image%202026-07-21%20at%2011.32.34%20AM.jpeg",
        "width": 1080,
        "height": 1448
      }
    ]
  },
  {
    "slug": "portfolio-9",
    "folder": "Portfolio-9",
    "title": "Project 09",
    "category": "Branding",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-9/WhatsApp%20Image%202026-07-21%20at%2011.35.13%20AM.jpeg",
      "width": 1600,
      "height": 583
    },
    "images": [
      {
        "src": "/Portfolio-9/WhatsApp%20Image%202026-07-21%20at%2011.35.13%20AM.jpeg",
        "width": 1600,
        "height": 583
      },
      {
        "src": "/Portfolio-9/WhatsApp%20Image%202026-07-21%20at%2011.36.41%20AM%20(1).jpeg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/Portfolio-9/WhatsApp%20Image%202026-07-21%20at%2011.36.41%20AM%20(2).jpeg",
        "width": 1080,
        "height": 1080
      },
      {
        "src": "/Portfolio-9/WhatsApp%20Image%202026-07-21%20at%2011.36.41%20AM.jpeg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/Portfolio-9/WhatsApp%20Image%202026-07-21%20at%2011.36.47%20AM.jpeg",
        "width": 1254,
        "height": 1254
      }
    ]
  },
  {
    "slug": "portfolio-10",
    "folder": "Portfolio-10",
    "title": "Project 10",
    "category": "Social Media",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.37.13%20AM.jpeg",
      "width": 1600,
      "height": 583
    },
    "images": [
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.37.13%20AM.jpeg",
        "width": 1600,
        "height": 583
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.37.16%20AM.jpeg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.39.38%20AM.jpeg",
        "width": 1600,
        "height": 1600
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.40.15%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.40.16%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.40.16%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.40.17%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.40.17%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.40.18%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.40.18%20AM%20(2).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.40.18%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-10/WhatsApp%20Image%202026-07-21%20at%2011.40.19%20AM.jpeg",
        "width": 1200,
        "height": 1600
      }
    ]
  },
  {
    "slug": "portfolio-11",
    "folder": "Portfolio-11",
    "title": "Project 11",
    "category": "Packaging",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-11/WhatsApp%20Image%202026-07-21%20at%2011.40.44%20AM.jpeg",
      "width": 1600,
      "height": 900
    },
    "images": [
      {
        "src": "/Portfolio-11/WhatsApp%20Image%202026-07-21%20at%2011.40.44%20AM.jpeg",
        "width": 1600,
        "height": 900
      },
      {
        "src": "/Portfolio-11/WhatsApp%20Image%202026-07-21%20at%2011.42.44%20AM%20(1).jpeg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/Portfolio-11/WhatsApp%20Image%202026-07-21%20at%2011.42.44%20AM%20(2).jpeg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/Portfolio-11/WhatsApp%20Image%202026-07-21%20at%2011.42.44%20AM.jpeg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/Portfolio-11/WhatsApp%20Image%202026-07-21%20at%2011.42.45%20AM%20(1).jpeg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/Portfolio-11/WhatsApp%20Image%202026-07-21%20at%2011.42.45%20AM%20(2).jpeg",
        "width": 1080,
        "height": 1440
      },
      {
        "src": "/Portfolio-11/WhatsApp%20Image%202026-07-21%20at%2011.42.45%20AM.jpeg",
        "width": 1080,
        "height": 1440
      }
    ]
  },
  {
    "slug": "portfolio-12",
    "folder": "Portfolio-12",
    "title": "Project 12",
    "category": "Illustration",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.06%20AM%20(1).jpeg",
      "width": 1600,
      "height": 1067
    },
    "images": [
      {
        "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.06%20AM%20(1).jpeg",
        "width": 1600,
        "height": 1067
      },
      {
        "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.06%20AM.jpeg",
        "width": 1600,
        "height": 1067
      },
      {
        "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.07%20AM%20(1).jpeg",
        "width": 1600,
        "height": 1067
      },
      {
        "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.07%20AM%20(2).jpeg",
        "width": 1600,
        "height": 1067
      },
      {
        "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.07%20AM%20(3).jpeg",
        "width": 1600,
        "height": 1200
      },
      {
        "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.07%20AM%20(4).jpeg",
        "width": 1600,
        "height": 1200
      },
      {
        "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.07%20AM.jpeg",
        "width": 1600,
        "height": 1067
      },
      {
        "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.19%20AM.jpeg",
        "width": 1280,
        "height": 1600
      },
      {
        "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.21%20AM.jpeg",
        "width": 1600,
        "height": 1067
      },
      {
        "src": "/Portfolio-12/WhatsApp%20Image%202026-07-21%20at%2011.43.22%20AM.jpeg",
        "width": 1600,
        "height": 1080
      }
    ]
  },
  {
    "slug": "portfolio-13",
    "folder": "Portfolio-13",
    "title": "Project 13",
    "category": "Branding",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.44.32%20AM.jpeg",
      "width": 1600,
      "height": 1018
    },
    "images": [
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.44.32%20AM.jpeg",
        "width": 1600,
        "height": 1018
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.04%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.05%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.05%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.06%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.06%20AM%20(2).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.06%20AM%20(3).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.06%20AM%20(4).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.06%20AM%20(5).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.06%20AM.jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.07%20AM%20(1).jpeg",
        "width": 1200,
        "height": 1600
      },
      {
        "src": "/Portfolio-13/WhatsApp%20Image%202026-07-21%20at%2011.45.07%20AM.jpeg",
        "width": 1200,
        "height": 1600
      }
    ]
  },
  {
    "slug": "portfolio-14",
    "folder": "Portfolio-14",
    "title": "Project 14",
    "category": "Social Media",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.18%20AM%20(1).jpeg",
      "width": 1280,
      "height": 853
    },
    "images": [
      {
        "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.18%20AM%20(1).jpeg",
        "width": 1280,
        "height": 853
      },
      {
        "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.18%20AM.jpeg",
        "width": 1280,
        "height": 1024
      },
      {
        "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.45%20AM%20(1).jpeg",
        "width": 589,
        "height": 1280
      },
      {
        "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.45%20AM%20(2).jpeg",
        "width": 589,
        "height": 1280
      },
      {
        "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.45%20AM%20(3).jpeg",
        "width": 589,
        "height": 1280
      },
      {
        "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.45%20AM.jpeg",
        "width": 589,
        "height": 1280
      },
      {
        "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.46%20AM%20(1).jpeg",
        "width": 589,
        "height": 1280
      },
      {
        "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.46%20AM%20(2).jpeg",
        "width": 589,
        "height": 1280
      },
      {
        "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.46%20AM%20(3).jpeg",
        "width": 589,
        "height": 1280
      },
      {
        "src": "/Portfolio-14/WhatsApp%20Image%202026-07-21%20at%2011.45.46%20AM.jpeg",
        "width": 589,
        "height": 1280
      }
    ]
  },
  {
    "slug": "portfolio-15",
    "folder": "Portfolio-15",
    "title": "Project 15",
    "category": "Packaging",
    "year": "2026",
    "description": "",
    "cover": {
      "src": "/Portfolio-15/10%20YEARS-09.jpg",
      "width": 6767,
      "height": 3779
    },
    "images": [
      {
        "src": "/Portfolio-15/10%20YEARS-09.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-10.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-11.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-12.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-13.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-14.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-15.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-16.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-17.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-18.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-19.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-20.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-21.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-22.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-23.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-24.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-25.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-26.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-27.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-28.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-29.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-30.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-31.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-32.jpg",
        "width": 6767,
        "height": 3779
      },
      {
        "src": "/Portfolio-15/10%20YEARS-33.jpg",
        "width": 6767,
        "height": 3779
      }
    ]
  }
];
